"""
Property-based tests for schema context correctness in prompt templates.

Uses Hypothesis to verify that the schema context generated by SchemaRegistry
contains correct keys and excludes phantom keys.

Feature: schema-alignment-dynamic-columns
"""

from unittest.mock import patch, MagicMock

import pytest
from hypothesis import given, settings, assume
from hypothesis import strategies as st

from app.services.schema_registry import SchemaRegistry


# ---------------------------------------------------------------------------
# Strategies
# ---------------------------------------------------------------------------

# Generate valid source_table names (start with uppercase letter)
_source_table_strategy = st.text(
    alphabet=st.sampled_from("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz_"),
    min_size=2,
    max_size=20,
).filter(lambda s: s[0].isupper())

# Generate valid metadata key names
_key_strategy = st.text(
    alphabet=st.sampled_from("abcdefghijklmnopqrstuvwxyz_ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"),
    min_size=1,
    max_size=30,
)

# Generate a schema: dict of source_table -> list of unique keys
_schema_strategy = st.dictionaries(
    keys=_source_table_strategy,
    values=st.lists(_key_strategy, min_size=1, max_size=10, unique=True),
    min_size=1,
    max_size=8,
)

# Phantom keys that must NOT appear as GLOBAL keys
CASHFLOW_PHANTOMS = {"Inflow", "Outflow", "Balance"}
EXPENSES_PHANTOMS = {"Description", "Supplier", "Method", "Remarks"}
ALL_PHANTOMS = CASHFLOW_PHANTOMS | EXPENSES_PHANTOMS


def _schema_to_db_rows(schema: dict) -> list:
    """Convert a {source_table: [keys]} dict into flat DB row format."""
    rows = []
    for table, keys in schema.items():
        for key in keys:
            rows.append({"source_table": table, "key": key})
    return rows


def _make_registry_with_schema(schema: dict) -> SchemaRegistry:
    """Create a SchemaRegistry pre-loaded with the given schema (no DB calls)."""
    registry = SchemaRegistry.__new__(SchemaRegistry)
    registry._cache = {k: list(v) for k, v in schema.items()}
    registry._cache_time = float("inf")  # never expires
    registry._ttl = SchemaRegistry.DEFAULT_TTL
    return registry


# ---------------------------------------------------------------------------
# Property 1: Schema context contains correct keys and excludes phantom keys
# ---------------------------------------------------------------------------


class TestProperty1SchemaContextCorrectness:
    """
    # Feature: schema-alignment-dynamic-columns, Property 1: Schema context contains correct keys and excludes phantom keys

    **Validates: Requirements 1.1, 1.3, 2.1, 2.2, 3.1, 4.1, 5.1, 6.4, 10.1, 10.2, 10.3, 11.2**
    """

    @given(schema=_schema_strategy)
    @settings(max_examples=100)
    def test_schema_context_contains_all_registered_keys(self, schema: dict):
        """For each source_table in the schema, all its keys appear in the context string.

        **Validates: Requirements 1.1, 2.1, 3.1, 4.1, 5.1, 6.4, 11.2**
        """
        registry = _make_registry_with_schema(schema)
        context = registry.build_schema_context()

        for table, keys in schema.items():
            assert table in context, (
                f"Source table '{table}' not found in schema context"
            )
            for key in keys:
                assert key in context, (
                    f"Key '{key}' for table '{table}' not found in schema context"
                )

    @given(schema=_schema_strategy)
    @settings(max_examples=100)
    def test_schema_context_contains_all_source_table_names(self, schema: dict):
        """All source table names appear in the schema context.

        **Validates: Requirements 10.1, 10.2, 10.3, 11.2**
        """
        registry = _make_registry_with_schema(schema)
        context = registry.build_schema_context()

        for table in schema:
            assert f"Source Table: {table}" in context, (
                f"Source table header 'Source Table: {table}' not found in context"
            )

    def test_global_schema_all_five_tables_in_context(self):
        """All 5 GLOBAL_SCHEMA source tables appear in the schema context.

        **Validates: Requirements 1.1, 2.1, 3.1, 4.1, 5.1, 10.1**
        """
        registry = _make_registry_with_schema(SchemaRegistry.GLOBAL_SCHEMA)
        context = registry.build_schema_context()

        expected_tables = ["Expenses", "CashFlow", "Project", "Quotation", "QuotationItem"]
        for table in expected_tables:
            assert table in context, (
                f"Expected source table '{table}' not found in schema context"
            )

    def test_phantom_keys_not_in_global_schema_context(self):
        """Phantom keys must NOT appear as GLOBAL keys in the schema context.

        CashFlow phantoms: Inflow, Outflow, Balance
        Expenses phantoms: Description, Supplier, Method, Remarks

        **Validates: Requirements 1.1, 1.3, 2.1, 2.2**
        """
        registry = _make_registry_with_schema(SchemaRegistry.GLOBAL_SCHEMA)
        context = registry.build_schema_context()

        for phantom in ALL_PHANTOMS:
            assert phantom not in context, (
                f"Phantom key '{phantom}' found in GLOBAL schema context — "
                f"this key should not be a GLOBAL metadata key"
            )

    @given(
        extra_keys=st.lists(
            st.text(
                alphabet=st.sampled_from("abcdefghijklmnopqrstuvwxyz_"),
                min_size=3,
                max_size=20,
            ).filter(lambda k: k not in ALL_PHANTOMS),
            min_size=1,
            max_size=5,
            unique=True,
        )
    )
    @settings(max_examples=100)
    def test_custom_columns_appear_in_context(self, extra_keys: list):
        """Dynamically discovered custom columns appear in the schema context.

        Simulates custom columns added to Expenses (e.g., "Driver", "truck_id").

        **Validates: Requirements 6.4, 11.2**
        """
        # Start from GLOBAL_SCHEMA and add custom keys to Expenses
        schema = {k: list(v) for k, v in SchemaRegistry.GLOBAL_SCHEMA.items()}
        schema["Expenses"] = schema["Expenses"] + extra_keys

        registry = _make_registry_with_schema(schema)
        context = registry.build_schema_context()

        for key in extra_keys:
            assert key in context, (
                f"Custom key '{key}' not found in schema context after discovery"
            )

    @given(schema=_schema_strategy)
    @settings(max_examples=100)
    def test_phantom_keys_excluded_even_with_random_schemas(self, schema: dict):
        """Phantom keys should not appear in context unless explicitly in the schema.

        If the generated schema happens to include a phantom key, that's fine —
        we only check that GLOBAL_SCHEMA doesn't contain them.

        **Validates: Requirements 1.3, 2.2**
        """
        # Use GLOBAL_SCHEMA specifically — phantom keys must not be there
        global_schema = SchemaRegistry.GLOBAL_SCHEMA

        # Verify at the data level: no phantom key in GLOBAL_SCHEMA values
        for table, keys in global_schema.items():
            for key in keys:
                assert key not in ALL_PHANTOMS, (
                    f"Phantom key '{key}' found in GLOBAL_SCHEMA['{table}'] — "
                    f"GLOBAL_SCHEMA must not contain phantom keys"
                )

    @given(
        schema=st.fixed_dictionaries({
            "Expenses": st.just(["Category", "Expenses", "Name"]),
            "CashFlow": st.just(["Type", "Amount", "Category"]),
            "Project": st.just(["project_name", "client_name", "location", "status"]),
            "Quotation": st.just(["quote_number", "status", "total_amount", "project_name"]),
            "QuotationItem": st.just(["plate_no", "dr_no", "material", "quarry_location",
                                      "truck_type", "volume", "line_total"]),
        })
    )
    @settings(max_examples=100)
    def test_build_system_prompt_includes_dynamic_schema(self, schema: dict):
        """build_system_prompt() includes the dynamic schema context from SchemaRegistry.

        **Validates: Requirements 6.4, 10.1, 10.2, 10.3**
        """
        registry = _make_registry_with_schema(schema)

        with patch("app.config.prompt_templates.get_schema_registry", return_value=registry):
            from app.config.prompt_templates import build_system_prompt
            prompt = build_system_prompt()

        # All source tables and their keys should be in the assembled prompt
        for table, keys in schema.items():
            assert table in prompt, (
                f"Source table '{table}' not found in build_system_prompt() output"
            )
            for key in keys:
                assert key in prompt, (
                    f"Key '{key}' for table '{table}' not in build_system_prompt() output"
                )

        # Phantom keys must not appear in the dynamic schema portion
        for phantom in ALL_PHANTOMS:
            assert phantom not in registry.build_schema_context(), (
                f"Phantom key '{phantom}' found in dynamic schema context"
            )


# ---------------------------------------------------------------------------
# Unit tests for prompt templates — SYSTEM_IDENTITY and schema context
# ---------------------------------------------------------------------------


class TestPromptTemplatesUnit:
    """
    Unit tests verifying SYSTEM_IDENTITY content and schema context correctness.

    **Validates: Requirements 10.1, 10.2, 10.3**
    """

    # ------------------------------------------------------------------
    # SYSTEM_IDENTITY tests
    # ------------------------------------------------------------------

    def test_system_identity_mentions_all_five_source_tables(self):
        """SYSTEM_IDENTITY must mention all 5 source tables.

        **Validates: Requirement 10.1**
        """
        from app.config.prompt_templates import SYSTEM_IDENTITY

        for table in ["Expenses", "CashFlow", "Project", "Quotation", "QuotationItem"]:
            assert table in SYSTEM_IDENTITY, (
                f"SYSTEM_IDENTITY does not mention source table '{table}'"
            )

    def test_system_identity_mentions_project_capabilities(self):
        """SYSTEM_IDENTITY must mention project detail capabilities.

        **Validates: Requirement 10.2**
        """
        from app.config.prompt_templates import SYSTEM_IDENTITY

        identity_lower = SYSTEM_IDENTITY.lower()
        assert "project" in identity_lower, (
            "SYSTEM_IDENTITY does not mention project capabilities"
        )
        # Should mention project-related lookup abilities
        assert any(
            phrase in identity_lower
            for phrase in ["project details", "project detail", "clients", "locations", "statuses"]
        ), "SYSTEM_IDENTITY does not describe project detail capabilities (clients, locations, statuses)"

    def test_system_identity_mentions_quotation_capabilities(self):
        """SYSTEM_IDENTITY must mention quotation data capabilities.

        **Validates: Requirement 10.2**
        """
        from app.config.prompt_templates import SYSTEM_IDENTITY

        identity_lower = SYSTEM_IDENTITY.lower()
        assert "quotation" in identity_lower, (
            "SYSTEM_IDENTITY does not mention quotation capabilities"
        )
        assert any(
            phrase in identity_lower
            for phrase in ["quotation data", "quote numbers", "quote number", "totals"]
        ), "SYSTEM_IDENTITY does not describe quotation data capabilities"

    def test_system_identity_mentions_delivery_capabilities(self):
        """SYSTEM_IDENTITY must mention delivery/line item capabilities.

        **Validates: Requirement 10.2**
        """
        from app.config.prompt_templates import SYSTEM_IDENTITY

        identity_lower = SYSTEM_IDENTITY.lower()
        assert any(
            phrase in identity_lower
            for phrase in ["delivery", "line item", "plate number", "dr number", "materials", "volumes"]
        ), "SYSTEM_IDENTITY does not describe delivery/line item capabilities"

    # ------------------------------------------------------------------
    # Schema context tests (using GLOBAL_SCHEMA via mocked registry)
    # ------------------------------------------------------------------

    def _build_global_schema_context(self) -> str:
        """Helper: build schema context from GLOBAL_SCHEMA."""
        registry = _make_registry_with_schema(SchemaRegistry.GLOBAL_SCHEMA)
        return registry.build_schema_context()

    def test_schema_context_includes_project_keys(self):
        """Schema context from GLOBAL_SCHEMA includes Project keys.

        **Validates: Requirement 10.2**
        """
        context = self._build_global_schema_context()
        for key in ["project_name", "client_name", "location", "status"]:
            assert key in context, (
                f"Project key '{key}' not found in schema context"
            )

    def test_schema_context_includes_quotation_keys(self):
        """Schema context from GLOBAL_SCHEMA includes Quotation keys.

        **Validates: Requirement 10.2**
        """
        context = self._build_global_schema_context()
        for key in ["quote_number", "status", "total_amount", "project_name"]:
            assert key in context, (
                f"Quotation key '{key}' not found in schema context"
            )

    def test_schema_context_includes_quotation_item_keys(self):
        """Schema context from GLOBAL_SCHEMA includes QuotationItem keys.

        **Validates: Requirement 10.2**
        """
        context = self._build_global_schema_context()
        for key in ["plate_no", "dr_no", "material", "quarry_location",
                     "truck_type", "volume", "line_total"]:
            assert key in context, (
                f"QuotationItem key '{key}' not found in schema context"
            )

    def test_no_phantom_keys_in_schema_context(self):
        """Schema context from GLOBAL_SCHEMA must NOT contain phantom keys.

        CashFlow phantoms: Inflow, Outflow, Balance
        Expenses phantoms: Description, Supplier, Method, Remarks

        **Validates: Requirement 10.3**
        """
        context = self._build_global_schema_context()
        for phantom in ALL_PHANTOMS:
            assert phantom not in context, (
                f"Phantom key '{phantom}' found in GLOBAL schema context"
            )
