-- Migration: Add pgvector extension and embedding column to ai_documents
-- Purpose: Enable semantic search using vector similarity
-- Date: 2026-02-13

-- Step 1: Enable pgvector extension
CREATE EXTENSION IF NOT EXISTS vector;

-- Step 2: Add embedding column to ai_documents table
-- 768 dimensions matches multilingual-e5-base model output
ALTER TABLE ai_documents 
ADD COLUMN IF NOT EXISTS embedding vector(768);

-- Step 3: Create IVFFlat index for fast vector similarity search
-- Using cosine distance operator (<=>)
-- lists=100 is optimal for datasets with 10k-100k rows
CREATE INDEX IF NOT EXISTS ai_documents_embedding_idx 
ON ai_documents 
USING ivfflat (embedding vector_cosine_ops)
WITH (lists = 100);

-- Step 4: Add comment for documentation
COMMENT ON COLUMN ai_documents.embedding IS 'Semantic embedding vector (768-dim) generated by multilingual-e5-base model for similarity search';

-- Verification query (optional - for testing)
-- SELECT COUNT(*) as total_docs, 
--        COUNT(embedding) as docs_with_embeddings,
--        COUNT(*) - COUNT(embedding) as docs_without_embeddings
-- FROM ai_documents;
